# Generated by Django 6.0.3 on 2026-04-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='faculty/')),
                ('designation', models.CharField(choices=[('Director', 'Director'), ('Faculty Teacher', 'Faculty Teacher'), ('HOD', 'HOD')], max_length=100)),
            ],
        ),
    ]
