# Generated by Django 6.0.3 on 2026-04-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('Event', 'Event'), ('Result_banner', 'Result_banner'), ('Teacher Banner', 'Teacher Banner')], max_length=50),
        ),
    ]
