# Generated by Django 6.0.3 on 2026-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_course_options_alter_enquiry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('1st to 7th class', '1st to 7th class'), ('8th class', '8th class'), ('10th class', '10th class'), ('11th Arts', '11th Arts'), ('11th Science', '11th Science'), ('12th Arts', '12th Arts'), ('12th Science', '12th Science')], default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
