# Generated by Django 6.0.3 on 2026-04-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_course_name_course_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500)),
                ('video_title', models.CharField(max_length=70)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='youtube_thumbnail/')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
