# Generated by Django 6.0.3 on 2026-04-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
