# Generated by Django 6.0.3 on 2026-04-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_videos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_thumbnail',
        ),
    ]
