# Generated by Django 6.0.3 on 2026-04-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_video_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_title',
            field=models.CharField(auto_created=True, max_length=70),
        ),
    ]
