# Generated by Django 6.0.3 on 2026-04-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_video_options_video_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('Event', 'Event'), ('Result banner', 'Result banner'), ('Teacher Banner', 'Teacher Banner')], max_length=50),
        ),
    ]
